from colored import fg, bg, attr
import time

 
time.sleep(3)
print(f"{fg(103)}\n\n\n╔══════════════════Credits═══════════════════╗{attr(0)}")
time.sleep(0.1)
print(f"{fg(103)}║                                            ║{attr(0)}")
time.sleep(0.1)
print(f"{fg(103)}║                    ~~~~                    ║{attr(0)}")
time.sleep(0.1)
print(f"{fg(103)}║             Executive producers            ║{attr(0)}")
time.sleep(0.1)
print(f"{fg(103)}║                                            ║{attr(0)}")
time.sleep(0.1)
print(f"{fg(103)}║                 Diego Amati                ║{attr(0)}")
time.sleep(0.1)
print(f"{fg(103)}║               Nicola Tonelli               ║{attr(0)}")
time.sleep(0.1)
print(f"{fg(103)}║                Paolo D'Elia                ║{attr(0)}")
time.sleep(0.1)
print(f"{fg(103)}║                    ~~~~                    ║{attr(0)}")
time.sleep(0.1)
print(f"{fg(103)}║                                            ║{attr(0)}")
time.sleep(0.1)
print(f"{fg(103)}║           {fg(160)}Thank you for playing!{attr(0)}{fg(103)}           ║{attr(0)}")
time.sleep(0.1)
print(f"{fg(103)}║                                            ║{attr(0)}")
time.sleep(0.1)
print(f"{fg(103)}║                    ~~~~                    ║{attr(0)}")
time.sleep(0.1)
print(f"{fg(103)}║                                            ║{attr(0)}")
time.sleep(0.1)
print(f"{fg(103)}║   PKM Project   |   3M inc. © 2020-2023    ║{attr(0)}")
time.sleep(0.1)
print(f"{fg(103)}║            All rights reserved             ║{attr(0)}")
time.sleep(0.1)
print(f"{fg(103)}╚════════════════════════════════════════════╝{attr(0)}")
